/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Rick and Morty API (Custom Swagger)
 * Документация для публичного Rick and Morty API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export type GetCharacterParams = {
  /**
   * Номер страницы
   */
  page?: number;
  /**
   * Поиск по имени
   */
  name?: string;
};

export const getRickAndMortyAPICustomSwagger = () => {
  /**
   * @summary Получить список персонажей
   */
  const getCharacter = <TData = AxiosResponse<void>>(
    params?: GetCharacterParams,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/character`, {
      ...options,
      params: { ...params, ...options?.params }
    });
  };

  /**
   * @summary Получить персонажа по ID
   */
  const getCharacterId = <TData = AxiosResponse<void>>(
    id: number,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.default.get(`/character/${id}`, options);
  };

  return { getCharacter, getCharacterId };
};

export type GetCharacterResult = AxiosResponse<void>;
export type GetCharacterIdResult = AxiosResponse<void>;
